config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new]
  resources :materials do 
    member do 
      patch :check_in
    end
  end
  resources :material_stocks
  resources :logs, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :material_stock
  belongs_to :user

  validates :action, presence: true

  has_enumeration_for :action, with: Movement, create_scopes: true, create_helpers: true
end

app/models/material.rb
class Material < ApplicationRecord
  has_one :material_stock
  validates :name, presence: true, uniqueness: true

end

app/models/material_stock.rb
class MaterialStock < ApplicationRecord
  belongs_to :material
  validates :material, uniqueness: { scope: :material_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, :password, presence: true

  has_many :material_stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CommonApiOptions

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

  def paginate_params
    params.permit(:page, :per_page)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    CRUDManagement::Index.perform(
      paginate_params.merge(ransack_params: ransack_options),
      default_index_callbacks,
      scope
    )
  end

  private

  def scope
    Log.joins(:material_stock).where(material_stocks: {material_id: material_id})
  end

  def material_id
    params.require(:log).permit(:material_id)[:material_id]
  end 
end

app/controllers/material_stocks_controller.rb
class MaterialStocksController < ApplicationController
  def new
    @material_id = material_stock_params[:material_id]
    @flag = material_stock_params[:flag]
    material_stock = MaterialStock.new
  end
  
  def index
    CRUDManagement::Index.perform(
      paginate_params.merge(ransack_params: ransack_options),
      { success: success_callbacks, error: error_callbacks },
      Material
    )
  end

  def show

  end

  def create
    MaterialStockManagement::Create.perform(
      material_stock_params.merge(quantity: params[:quantity], current_user_id: session[:user_id]),
      { success: success_callbacks, error: error_callbacks },
      MaterialStock
    )
  end

  def update

  end

  def destroy
    MaterialManagement::Destroy.perform(
      find_params,
      { success: success_callbacks, error: error_callbacks },
      Material
    )
  end

  private

  def success_callbacks
    lambda do |caller|
      @items = caller
      redirect_to materials_path
    end
  end

  def error_callbacks
    lambda do |caller|
      flash[:alert] = caller.errors.errors.last.type
      redirect_to materials_path
    end
  end

  def material_stock_params
    params.require(:material_stock).permit(:id, :material_id, :quantity, :flag)
  end


  def find_params
    { id: params.require(:id) }
  end 
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def new
    @user = Material.new
  end
  
  def index
    CRUDManagement::Index.perform(
      paginate_params.merge(ransack_params: ransack_options),
      { success: success_callbacks, error: error_callbacks },
      search.present? ? Material.where(name: search) : Material
    )
  end

  def create
    success_callbacks = lambda do |caller|
      @items = caller
      redirect_to materials_path
    end
    CRUDManagement::Create.perform(
      material_params,
      { success: success_callbacks, error: error_callbacks },
      Material
    )
  end

  def edit
    @material = Material.find_by(find_params)
  end


  def update
    success_callbacks = lambda do |caller|
      redirect_to materials_path
    end

    CRUDManagement::Update.perform(
      find_params,
      material_update_params,
      { success: success_callbacks, error: error_callbacks },
      Material
    )
  end

  def destroy
    MaterialManagement::Destroy.perform(
      find_params,
      { success: success_callbacks, error: error_callbacks },
      Material
    )
  end

  private

  def success_callbacks
    lambda do |caller|
      @items = caller
    end
  end

  def error_callbacks
    lambda do |caller|
      flash[:alert] = caller.errors.errors.last.type
    end
  end

  def material_params
    params.permit(:name)
  end

  def material_update_params
    params.require(:material).permit(:name)
  end

  def search
    params[:search]
  end

  def find_params
    { id: params.require(:id) }
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    session[:user_id] = nil
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logado com sucesso."
      redirect_to materials_path
    else
      flash.now[:alert] = "Problemas na autenticação."
      render 'new'
    end
  end
   
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created."
      redirect_to login_path
    else
      render 'new'
    end
  end

  def index
    CRUDManagement::Index.perform(
      paginate_params.merge(ransack_params: ransack_options),
      default_index_callbacks,
      User
    )
  end
  
 private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_per_field(object, field)
    return if object.errors.blank?

    object.errors.filter { |e| e.attribute.eql?(field.to_sym) }.first&.full_message
  end

  def flash_message_classes(flash_type, message)
    {
      notice: message,
      error: message,
      alert: message
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Materials</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <%= render 'shared/flash_messages' %>
     <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" style="font-size:30px">Usuários</a>
    <a class="navbar-brand" href="../materials">Materiais <span class="sr-only">(current)</span></a>
    <a class="navbar-brand" href="login">Sair <span class="sr-only"></span></a>
</nav>

<div id="materials">
  <table class="table">
    <thead>
     <tr>
       <th scope="col">id</th>
       <th scope="col">Informação</th>
      </tr>
   </thead>
   <% @items.each do |log| %>  
    <tbody>
     <tr>
        <th scope="row"><%= log.id%></th>
        <td><%= "#{log.user.username} #{log.action.eql?(Movement::ADD) ? "adicionou" : "removeu"} #{log.quantity} items de #{log.material_stock.material.name}"%></td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>

<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>
</div>

app/views/material_stocks/new.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#" style="font-size: 30px">Entrada/Saída nos materiais</a>
  </nav>
  <div class="d-flex flex justify-content-center" style="margin: 10px; width: 60rem; margin-top: 50px;">
  <p style="font-size: 24px; font-weight: 900"></p>
  <%= form_with(model: @material_stock, url: material_stocks_path(material_stock: { material_id: @material_id, flag: @flag}), html: { method: :post }) do |f| %>
    <div class="mb-3">
      <label for="exampleInputName1" class="form-label">Quantidade</label>
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
    <div class="mb-3 form-group" style="margin-top: 10px">
      <%= f.submit "Cadastrar", class: "btn btn-primary"%>
    </div>
  <% end %>
  </div>
<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>
</div>

app/views/materials/edit.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#" style="font-size: 30px">Editar material</a>
  </nav>
  <div class="d-flex flex justify-content-center" style="margin: 10px; width: 60rem; margin-top: 50px;">
  <p style="font-size: 24px; font-weight: 900"></p>
  <%= form_with(model: @material, url: material_path, html: { method: :patch }) do |f| %>
    <div class="mb-3">
      <label for="exampleInputName1" class="form-label">Novo nome</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3 form-group" style="margin-top: 10px">
      <%= f.submit "Salvar", class: "btn btn-primary"%>
    </div>
  <% end %>
  </div>

<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>
</div>

app/views/materials/index.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" style="font-size:30px">Materiais</a>
    <a class="navbar-brand" href="../users">Usuários <span class="sr-only">(current)</span></a>
    <a class="navbar-brand" href="materials/new">Novo material <span class="sr-only"></span></a>
    <a class="navbar-brand" href="login">Sair <span class="sr-only"></span></a>
</nav>

<div id="materials">
  <table class="table">
  <h4>Filtrar material</h4>
  <%= form_tag(materials_path, method: :get) do%>
  <%= text_field_tag(:search, params[:search])%>
  <%= submit_tag("Buscar")%>
  <% end %>
    <thead>
     <tr>
       <th scope="col">id</th>
       <th scope="col">Nome</th>
       <th scope="col">Items</th>
       <th scope="col">Entrada</th>
       <th scope="col">Saída</th>
       <th scope="col">Remover</th>
       <th scope="col">Movimentações</th>
       <th scope="col">Editar</th>
      </tr>
   </thead>
   <% @items.each do |material| %>  
    <tbody>
     <tr>
        <th scope="row"><%= material.id%></th>
        <td><%= material.name%></td>
        <td>
          <% if material.material_stock.nil? %> 
            0 
          <%else%> 
            <%= material.material_stock.quantity.to_i %> 
          <%end%> 
        </td>
        <td>
          <button type="button" class="btn btn-success">
           <%= link_to "Dar entrada", new_material_stock_path(material_stock: { material_id: material.id, flag: "add"} ) %> 
          </button>
        </td>
        <td> 
         <% if material&.material_stock&.quantity.to_i > 0%>
            <button type="button" class="btn btn-warning">
              <%= link_to "Saída", new_material_stock_path(material_stock: { material_id: material.id, flag: "remove"} ) %> 
            </button>
          <% else %>
            <button type="button" class="btn btn-warning">
              <label>Saída</label>
            </button>
          <%end%>
        </td>
        <td> <%= button_to "delete", material, :method => :delete %></td>
        <td>
          <button type="button" class="btn btn-link" href="/logs">
            <%= link_to "Movimentações", logs_path(log: { material_id: material.id } ) %> 
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-link" href="#">
            <%= link_to "Editar", edit_material_path(material) %>
          </button>
        </td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>
<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>
</div>

app/views/materials/new.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#" style="font-size:30px">Cadastro de materiais</a>
  </nav>
  <div class="d-flex flex justify-content-center" style="margin: 10px; width: 60rem; margin-top: 50px;">
  <p style="font-size: 24px; font-weight: 900"></p>
  <%= form_with(model: @material, url: materials_path, html: { method: :post }) do |f| %>
    <div class="mb-3">
      <label for="exampleInputName1" class="form-label">Nome</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3 form-group" style="margin-top: 10px">
      <%= f.submit "Cadastrar", class: "btn btn-primary"%>
    </div>
  <% end %>
  </div>

<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>

<div class="alert alert-danger" role="alert">
  <%= flash_message_classes(type, message) %>
</div>
<% end %>

app/views/users/index.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 150rem; margin-top: 50px;">
<% if logged_in?%>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" style="font-size:30px">Usuários</a>
    <a class="navbar-brand" href="../materials">Materiais <span class="sr-only">(current)</span></a>
    <a class="navbar-brand" href="login">Sair <span class="sr-only"></span></a>
</nav>

<div id="materials">
  <table class="table">
    <thead>
     <tr>
       <th scope="col">id</th>
       <th scope="col">Nome</th>
      </tr>
   </thead>
   <% @items.each do |user| %>  
    <tbody>
     <tr>
        <th scope="row"><%= user.id%></th>
        <td><%= user.username%></td>
      </tr>
      </tbody>
    <% end %>
  </table>
</div>

<% else %>
  <script>
    window.location.href="/login"
  </script>
<%end%>

</div>

app/views/users/new.html.erb
<div class="d-flex flex justify-content-center" style="margin: 20px; width: 60rem; margin-top: 50px;">
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#" style="font-size:30px">Cadastro de usuários</a>
  </nav>
  <p style="font-size: 24px; font-weight: 900"></p>
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="mb-3">
      <label for="exampleInputName1" class="form-label">Nome</label>
      <%= f.text_field :username, class: "form-control" %>
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Senha</label>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="mb-3 form-group" style="margin-top: 10px">
      <%= f.submit "Cadastrar", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Hello, rails!</h1>